server:
  port: 8989
spring:
  jpa:
    hibernate:
      ddl-auto: update  #create in dev
      #     ddl-auto: update  #create in production
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./app    #store DB in testfile for testing purpose

